municipalities = {
    "AC": ["Rio Branco", "Cruzeiro do Sul", "Sena Madureira", "Tarauacá", "Feijó", "Brasiléia", "Plácido de Castro", "Senador Guiomard", "Xapuri", "Assis Brasil"],
    "AL": ["Maceió", "Arapiraca", "Palmeira dos Índios", "Rio Largo", "Arapiraca", "Delmiro Gouveia", "Penedo", "Maragogi", "Coruripe", "Palmeira de Fora"],
    "AP": ["Macapá", "Santana", "Laranjal do Jari", "Oiapoque", "Tartarugalzinho", "Amapá", "Pedra Branca do Amapari", "Calçoene", "Cutias", "Itaubal"],
    "AM": ["Manaus", "Parintins", "Itacoatiara", "Manacapuru", "Tabatinga", "São Gabriel da Cachoeira", "Tefé", "Coari", "Maués", "Humaitá"],
    "BA": ["Salvador", "Feira de Santana", "Vitória da Conquista", "Camaçari", "Juazeiro", "Itabuna", "Ilhéus", "Lauro de Freitas", "Eunápolis", "Barreiras", "Porto Seguro", "Jequié", "Teixeira de Freitas", "Paulo Afonso"],
    "CE": ["Fortaleza", "Juazeiro do Norte", "Sobral", "Maracanaú", "Caucaia", "Crato", "Quixadá", "Aquiraz", "Itapipoca", "Limoeiro do Norte", "Russas", "Iguatu", "Aracati", "Canindé"],
    "DF": ["Brasília", "Taguatinga", "Ceilândia", "Águas Claras", "Gama", "Samambaia", "Planaltina", "Brazlândia", "Recanto das Emas", "Sobradinho"],
    "ES": ["Vitória", "Vila Velha", "Guarapari", "Serra", "Cariacica", "Linhares", "Colatina", "São Mateus", "Castelo", "Aracruz", "Iconha"],
    "GO": ["Goiânia", "Anápolis", "Aparecida de Goiânia", "Rio Verde", "Luziânia", "Formosa", "Catalão", "Jataí", "Águas Lindas de Goiás", "Trindade", "Itumbiara", "Caldas Novas", "Planaltina", "Morrinhos"],
    "MA": ["São Luís", "Imperatriz", "Timon", "Caxias", "Bacabal", "Açailândia", "Codó", "Pinheiro", "Chapadinha", "Santa Inês", "Balsas", "Viana", "Rosário", "Vargem Grande"],
    "MT": ["Cuiabá", "Várzea Grande", "Rondonópolis", "Sinop", "Cáceres", "Tangará da Serra", "Lucas do Rio Verde", "Campo Verde", "Sorriso", "Cuiabá", "Barra do Garças", "Colíder", "Água Boa", "Alta Floresta"],
    "MS": ["Campo Grande", "Dourados", "Três Lagoas", "Ponta Porã", "Corumbá", "Naviraí", "Paranaíba", "Sidrolândia", "Coxim", "Rio Verde de Mato Grosso", "Aquidauana", "Chapadão do Sul", "Itaquiraí", "Nova Andradina"],
    "MG": ["Belo Horizonte", "Uberlândia", "Contagem", "Juiz de Fora", "Betim", "Montes Claros", "Ipatinga", "Divinópolis", "Governador Valadares", "Sete Lagoas", "Teófilo Otoni", "Poços de Caldas", "Varginha", "Uberaba", "Patos de Minas"],
    "PA": ["Belém", "Ananindeua", "Santarém", "Marabá", "Parauapebas", "Castanhal", "Bragança", "Altamira", "Barcarena", "Capanema", "Conceição do Araguaia", "São Félix do Xingu", "Redenção", "Melgaço", "Tailândia"],
    "PB": ["João Pessoa", "Campina Grande", "Santa Rita", "Patos", "Bayeux", "Cabedelo", "Sousa", "Cajazeiras", "Pombal", "Itabaiana", "Monteiro", "Arapuan", "Sumé", "Guarabira", "Mamanguape"],
    "PR": ["Curitiba", "Londrina", "Maringá", "Cascavel", "Foz do Iguaçu", "Ponta Grossa", "São José dos Pinhais", "Guarapuava", "Paranaguá", "Arapongas", "Apucarana", "Toledo", "Lajeado", "Medianeira", "Umuarama"],
    "PE": ["Recife", "Jaboatão dos Guararapes", "Olinda", "Caruaru", "Petrolina", "Cabo de Santo Agostinho", "Vitória de Santo Antão", "Igarassu", "Paudalho", "Garanhuns", "Arcoverde", "Pesqueira", "Limoeiro", "Salgueiro"],
    "PI": ["Teresina", "Parnaíba", "Picos", "Floriano", "Esperantina", "Barrinhas", "Pedro II", "Bom Jesus", "Oeiras", "São Raimundo Nonato", "Barras", "União", "Cocal", "Canto do Buriti", "Miguel Alves"],
    "RJ": ["Rio de Janeiro", "Niterói", "Duque de Caxias", "Nova Iguaçu", "Campos dos Goytacazes", "São Gonçalo", "Teresópolis", "Petrópolis", "Volta Redonda", "Angra dos Reis", "Macuco", "Resende", "Barra Mansa", "Queimados"],
    "RN": ["Natal", "Mossoró", "Parnamirim", "Caicó", "Açú", "São Gonçalo do Amarante", "Santa Cruz", "Currais Novos", "Pau dos Ferros", "Assu", "Ceará-Mirim", "João Câmara", "Macau", "São José de Mipibu"],
    "RS": ["Porto Alegre", "Caxias do Sul", "Pelotas", "Santa Maria", "Gravataí", "São Leopoldo", "Novo Hamburgo", "Rio Grande", "Passo Fundo", "Bagé", "Lajeado", "Santa Cruz do Sul", "Uruguaiana", "Ijuí", "Sapiranga"],
    "RO": ["Porto Velho", "Ji-Paraná", "Ariquemes", "Rolim de Moura", "Jaru", "Vilhena", "Cacoal", "Guajará-Mirim", "Pimenta Bueno", "Nova Mamoré", "Colorado do Oeste", "Candeias do Jamari", "Alto Paraíso"],
    "RR": ["Boa Vista", "Rorainópolis", "Caracaraí", "São João da Baliza", "Bonfim", "Iracema", "Mucajaí", "Normandia", "Cantá", "Uiramutã"],
    "SC": ["Florianópolis", "Joinville", "Blumenau", "Criciúma", "Chapecó", "São José", "Lages", "Itajaí", "Brusque", "Jaraguá do Sul", "Balneário Camboriú", "Palhoça", "Camboriú", "Araranguá", "Rio do Sul"],
    "SP": ["São Paulo", "Campinas", "Santos", "São Bernardo do Campo", "São José dos Campos", "Sorocaba", "Ribeirão Preto", "São Caetano do Sul", "Guarulhos", "Osasco", "Mauá", "Bauru", "São Vicente", "Piracicaba", "Araraquara"],
    "SE": ["Aracaju", "Nossa Senhora do Socorro", "Lagarto", "Itabaiana", "Estância", "Tobias Barreto", "Propriá", "São Cristóvão", "Simão Dias", "Neópolis"],
    "TO": ["Palmas", "Araguaína", "Gurupi", "Paraíso do Tocantins", "Colinas do Tocantins", "Miracema do Tocantins", "Lajeado", "Porto Nacional", "Pedro Afonso", "Augustinópolis", "Filadélfia"]
}
