address = [
    {
        "CEP": "01311-000",
        "Street": "Avenida Paulista",
        "Number": "5659",
        "Complement": "até 609 - lado ímpar",
        "Neighborhood": "Bela Vista",
        "City": "São Paulo",
        "UF": "SP",
        "State": "São Paulo",
        "Region": "Sudeste",
        "IBGE Code": "3550308",
        "DDD": "11"
    },
    {
        "CEP": "22041-001",
        "Street": "Avenida Atlântica",
        "Number": "6925",
        "Complement": "de 2174 a 2634 - lado par",
        "Neighborhood": "Copacabana",
        "City": "Rio de Janeiro",
        "UF": "RJ",
        "State": "Rio de Janeiro",
        "Region": "Sudeste",
        "IBGE Code": "3304557",
        "DDD": "21"
    },
    {
        "CEP": "30130-110",
        "Street": "Alameda Ezequiel Dias",
        "Number": "8688",
        "Complement": "",
        "Neighborhood": "Centro",
        "City": "Belo Horizonte",
        "UF": "MG",
        "State": "Minas Gerais",
        "Region": "Sudeste",
        "IBGE Code": "3106200",
        "DDD": "31"
    },
    {
        "CEP": "80420-090",
        "Street": "Avenida do Batel",
        "Number": "8495",
        "Complement": "",
        "Neighborhood": "Batel",
        "City": "Curitiba",
        "UF": "PR",
        "State": "Paraná",
        "Region": "Sul",
        "IBGE Code": "4106902",
        "DDD": "41"
    },
    {
        "CEP": "90010-150",
        "Street": "Praça da Alfândega",
        "Number": "3642",
        "Complement": "",
        "Neighborhood": "Centro Histórico",
        "City": "Porto Alegre",
        "UF": "RS",
        "State": "Rio Grande do Sul",
        "Region": "Sul",
        "IBGE Code": "4314902",
        "DDD": "51"
    },
    {
        "CEP": "88015-400",
        "Street": "Rua Vítor Konder",
        "Number": "1941",
        "Complement": "",
        "Neighborhood": "Centro",
        "City": "Florianópolis",
        "UF": "SC",
        "State": "Santa Catarina",
        "Region": "Sul",
        "IBGE Code": "4205407",
        "DDD": "48"
    },
    {
        "CEP": "50030-230",
        "Street": "Cais do Apolo",
        "Number": "0586",
        "Complement": "",
        "Neighborhood": "Recife",
        "City": "Recife",
        "UF": "PE",
        "State": "Pernambuco",
        "Region": "Nordeste",
        "IBGE Code": "2611606",
        "DDD": "81"
    },
    {
        "CEP": "60125-120",
        "Street": "Rua Joaquim Nabuco",
        "Number": "5268",
        "Complement": "até 789/790",
        "Neighborhood": "Meireles",
        "City": "Fortaleza",
        "UF": "CE",
        "State": "Ceará",
        "Region": "Nordeste",
        "IBGE Code": "2304400",
        "DDD": "85"
    },
    {
        "CEP": "74015-070",
        "Street": "Rua 31",
        "Number": "0636",
        "Complement": "",
        "Neighborhood": "Setor Central",
        "City": "Goiânia",
        "UF": "GO",
        "State": "Goiás",
        "Region": "Centro-Oeste",
        "IBGE Code": "5208707",
        "DDD": "62"
    }
]
