address = [
    {
        "cep": "01311-000",
        "logradouro": "Avenida Paulista",
        "complemento": "até 609 - lado ímpar",
        "bairro": "Bela Vista",
        "localidade": "São Paulo",
        "uf": "SP",
        "estado": "São Paulo",
        "regiao": "Sudeste",
        "ibge": "3550308",
        "ddd": "11",
        "numero": "4882"
    },
    {
        "cep": "22041-001",
        "logradouro": "Avenida Atlântica",
        "complemento": "de 2174 a 2634 - lado par",
        "bairro": "Copacabana",
        "localidade": "Rio de Janeiro",
        "uf": "RJ",
        "estado": "Rio de Janeiro",
        "regiao": "Sudeste",
        "ibge": "3304557",
        "ddd": "21",
        "numero": "7829"
    },
    {
        "cep": "30130-110",
        "logradouro": "Alameda Ezequiel Dias",
        "complemento": "Aparatamento 202",
        "bairro": "Centro",
        "localidade": "Belo Horizonte",
        "uf": "MG",
        "estado": "Minas Gerais",
        "regiao": "Sudeste",
        "ibge": "3106200",
        "ddd": "31",
        "numero": "4315"
    },
    {
        "cep": "80420-090",
        "logradouro": "Avenida do Batel",
        "complemento": "Casa",
        "bairro": "Batel",
        "localidade": "Curitiba",
        "uf": "PR",
        "estado": "Paraná",
        "regiao": "Sul",
        "ibge": "4106902",
        "ddd": "41",
        "numero": "4608"
    },
    {
        "cep": "90010-150",
        "logradouro": "Praça da Alfândega",
        "complemento": "Perto da praça Vicente da Fontoura",
        "bairro": "Centro Histórico",
        "localidade": "Porto Alegre",
        "uf": "RS",
        "estado": "Rio Grande do Sul",
        "regiao": "Sul",
        "ibge": "4314902",
        "ddd": "51",
        "numero": "2215"
    },
    {
        "cep": "88015-400",
        "logradouro": "Rua Vítor Konder",
        "complemento": "Apartamento 101",
        "bairro": "Centro",
        "localidade": "Florianópolis",
        "uf": "SC",
        "estado": "Santa Catarina",
        "regiao": "Sul",
        "ibge": "4205407",
        "ddd": "48",
        "numero": "0062"
    },
    {
        "cep": "50030-230",
        "logradouro": "Cais do Apolo",
        "complemento": "Casa",
        "bairro": "Recife",
        "localidade": "Recife",
        "uf": "PE",
        "estado": "Pernambuco",
        "regiao": "Nordeste",
        "ibge": "2611606",
        "ddd": "81",
        "numero": "0242"
    },
    {
        "cep": "60125-120",
        "logradouro": "Rua Joaquim Nabuco",
        "complemento": "até 789/790",
        "bairro": "Meireles",
        "localidade": "Fortaleza",
        "uf": "CE",
        "estado": "Ceará",
        "regiao": "Nordeste",
        "ibge": "2304400",
        "ddd": "85",
        "numero": "6463"
    },
    {
        "cep": "74015-070",
        "logradouro": "Rua 31",
        "complemento": "",
        "bairro": "Setor Central",
        "localidade": "Goiânia",
        "uf": "GO",
        "estado": "Goiás",
        "regiao": "Centro-Oeste",
        "ibge": "5208707",
        "ddd": "62",
        "numero": "7203"
    }
]
