first_names = [
    "Adriana", "Aline", "Amanda", "Ana", "Andressa", "Beatriz", "Bruna",
    "Camila", "Carla", "Daniela", "Debora", "Eduarda", "Eliane", "Fernanda",
    "Gabriela", "Helena", "Isabela", "Juliana", "Larissa", "Leticia", "Lorena",
    "Luciana", "Marcela", "Mariana", "Natalia", "Patricia", "Rafaela", "Renata",
    "Sabrina", "Tatiana", "Vanessa", "Vitoria", "Yasmin", "Alice", "Bianca",
    "Caroline", "Cecilia", "Claudia", "Cristiane", "Daiane", "Diana", "Elisa",
    "Emanuelle", "Evelyn", "Fabiana", "Flavia", "Graziella", "Jessica", "Jennifer",
    "Joana", "Karla", "Kelly", "Livia", "Luana", "Michele", "Mirela", "Monica",
    "Priscila", "Regina", "Samara", "Simone", "Silvana", "Sueli", "Talita",
    "Valeria", "Vera", "Wilma", "Zuleide", "Adriano", "Alexandre", "Anderson",
    "Andre", "Antonio", "Bruno", "Caio", "Carlos", "Cesar", "Cristiano",
    "Daniel", "Davi", "Diego", "Douglas", "Eduardo", "Fabio", "Felipe",
    "Fernando", "Flavio", "Francisco", "Gabriel", "Guilherme", "Gustavo",
    "Henrique", "Hugo", "Igor", "Joao", "Jorge", "Jose", "Julio", "Leandro",
    "Leonardo", "Lucas", "Luiz", "Marcelo", "Marcos", "Mateus", "Mauricio",
    "Miguel", "Murilo", "Paulo", "Pedro", "Rafael", "Ramon", "Renato",
    "Ricardo", "Rodrigo", "Samuel", "Sergio", "Thiago", "Victor", "Vinicius",
    "Wagner", "William"
]
